### PR TITLE
Fix doc

### PR DESCRIPTION
**Pull request by k33g**
- Add clarification about `andThen`
- Fix sample

### CODE REVIEW

**Comment by yloiseau** [comment]
composition using `andThen` isnot limited to closures. You can use any function reference.

```golo
function foo = |x| -> x + 1
function bar = |x| -> 2 * x

let newFunction = ^foo: andThen(^bar)
```

**Comment by yloiseau** [comment]
Maybe “you can compose function and closure” woud be better.

BTW, to be pedantic, in the sample following the sentence, it's just anonymous functions, not closures, since no value is closed in the definition :wink:

**Comment by k33g** [comment]
argh you're right! :)

**Comment by k33g** [comment]
perhaps, this is the sample that isn't complete enough

**Pull request closed without merging**
